### ISSUE TITLE
Webdav as storage

### ISSUE THREAD

**Issue by kloenk** [totoval/mindav#3]
Is there a way to use the miniio and store that in a webdav? So that I store my minio files in my nextcloud?

**Comment by toby1991** [comment]
> Is there a way to use the miniio and store that in a webdav? So that I store my minio files in my nextcloud?

 Nextcloud or Owncloud support S3 backends by default.

**Comment by kloenk** [comment]
Unfortunately in my setup I only can use the webdav Backend, so I need a third party software on a different host to make me s3 from webdav

**Comment by toby1991** [comment]
You mean you wanna host a Minio server based on webdav protocol?
Or
Intergrate Minio into Owncloud/Nextcloud? (https://doc.owncloud.com/server/admin_manual/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.html)

**Comment by kloenk** [comment]
First. I want to host a minion with a webdav data Backend. So everything written to minio is written to the webdav storage

**Comment by toby1991** [comment]
> First. I want to host a minion with a webdav data Backend. So everything written to minio is written to the webdav storage

OK, This structure may cause some performance issues.
And `mindav` use webdav as minio backend, so this will not be supported.
